spring:
    environment: Local
    datasource:
        url: jdbc:mysql://localhost:3306/dbfiap?useTimezone=true&serverTimezone=UTC
        driver-class-name: 'com.mysql.cj.jdbc.Driver'
        username: root
        password: root
    filepath: /home/gui/Desktop/teste.csv
